# To see all available options, please visit the docs:
# https://docs.fossorial.io/Pangolin/Configuration/config

app:
    dashboard_url: "https://{{.DashboardDomain}}"
    log_level: "info"
    save_logs: false

domains:
    domain1:
        base_domain: "{{.BaseDomain}}"
        cert_resolver: "letsencrypt"

server:
    external_port: 3000
    internal_port: 3001
    next_port: 3002
    internal_hostname: "pangolin"
    session_cookie_name: "p_session_token"
    resource_access_token_param: "p_token"
    resource_access_token_headers:
        id: "P-Access-Token-Id"
        token: "P-Access-Token"
    resource_session_request_param: "p_session_request"
    secret: {{.Secret}}
    cors:
        origins: ["https://{{.DashboardDomain}}"]
        methods: ["GET", "POST", "PUT", "DELETE", "PATCH"]
        allowed_headers: ["X-CSRF-Token", "Content-Type"]
        credentials: false

traefik:
    cert_resolver: "letsencrypt"
    http_entrypoint: "web"
    https_entrypoint: "websecure"

gerbil:
    start_port: 51820
    base_endpoint: "{{.DashboardDomain}}"
    use_subdomain: false
    block_size: 24
    site_block_size: 30
    subnet_group: 100.89.137.0/20

rate_limits:
    global:
        window_minutes: 1
        max_requests: 500
{{if .EnableEmail}}
email:
    smtp_host: "{{.EmailSMTPHost}}"
    smtp_port: {{.EmailSMTPPort}}
    smtp_user: "{{.EmailSMTPUser}}"
    smtp_pass: "{{.EmailSMTPPass}}"
    no_reply: "{{.EmailNoReply}}"
{{end}}
users:
    server_admin:
        email: "{{.AdminUserEmail}}"
        password: "{{.AdminUserPassword}}"

flags:
    require_email_verification: {{.EnableEmail}}
    disable_signup_without_invite: {{.DisableSignupWithoutInvite}}
    disable_user_create_org: {{.DisableUserCreateOrg}}
    allow_raw_resources: true
    allow_base_domain_resources: true
